//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.ChiTietDonDatPhongs = new HashSet<ChiTietDonDatPhong>();
            this.PhongKhachHangs = new HashSet<PhongKhachHang>();
        }
    
        public int MaPhong { get; set; }
        public string TenPhong { get; set; }
        public int MaLoaiPhong { get; set; }
        public string ViTri { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> MaKhachSan { get; set; }
        public Nullable<int> DienTich { get; set; }
        public string HinhAnh { get; set; }
        public string NhomHinhAnh { get; set; }
        public string GioiThieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatPhong> ChiTietDonDatPhongs { get; set; }
        public virtual KhachSan KhachSan { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhongKhachHang> PhongKhachHangs { get; set; }
    }
}
